/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import HolidayParadise.CoursData;
import HolidayParadise.InstructorData;
import javax.swing.*;
/**
 *
 * @author Benedict
 */
public class MainFrame extends javax.swing.JFrame {
    
    private CoursData coursData = new CoursData();
    private InstructorData instructorData = new InstructorData();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        defaultPanel.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultPanel = new javax.swing.JPanel();
        coursPanel = new javax.swing.JPanel();
        coursLabel = new javax.swing.JLabel();
        coursCreateButton = new javax.swing.JButton();
        coursReadButton = new javax.swing.JButton();
        coursDeleteButton = new javax.swing.JButton();
        coursScrollPane = new javax.swing.JScrollPane();
        coursTable = new javax.swing.JTable();
        instrructorPanel = new javax.swing.JPanel();
        instructorLabel = new javax.swing.JLabel();
        instructorCreateButton = new javax.swing.JButton();
        instructorReadButton = new javax.swing.JButton();
        instructorDeleteButton = new javax.swing.JButton();
        instructorScrollPane = new javax.swing.JScrollPane();
        instructorTable = new javax.swing.JTable();
        customerPanel = new javax.swing.JPanel();
        customerLabel = new javax.swing.JLabel();
        customerCreateButton = new javax.swing.JButton();
        customerReadButton = new javax.swing.JButton();
        customerDeleteButton = new javax.swing.JButton();
        customerScrollPane = new javax.swing.JScrollPane();
        warningLabel = new javax.swing.JLabel();
        helpPanel = new javax.swing.JPanel();
        coursLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        coursLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        basicDataMenu = new javax.swing.JMenu();
        instructorMenuItem = new javax.swing.JMenuItem();
        customerMenuItem = new javax.swing.JMenuItem();
        coursMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        AboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        defaultPanel.setLayout(new java.awt.CardLayout());

        coursLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coursLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coursLabel.setText("Courses");

        coursCreateButton.setText("Create");
        coursCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursCreateButtonActionPerformed(evt);
            }
        });

        coursReadButton.setText("Read");
        coursReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursReadButtonActionPerformed(evt);
            }
        });

        coursDeleteButton.setText("Delete");
        coursDeleteButton.setToolTipText("");
        coursDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursDeleteButtonActionPerformed(evt);
            }
        });

        coursTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        coursScrollPane.setViewportView(coursTable);

        javax.swing.GroupLayout coursPanelLayout = new javax.swing.GroupLayout(coursPanel);
        coursPanel.setLayout(coursPanelLayout);
        coursPanelLayout.setHorizontalGroup(
            coursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coursLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(coursPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coursCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coursReadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coursDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(coursScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        coursPanelLayout.setVerticalGroup(
            coursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursPanelLayout.createSequentialGroup()
                .addComponent(coursLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coursScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(coursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coursCreateButton)
                    .addComponent(coursReadButton)
                    .addComponent(coursDeleteButton))
                .addContainerGap())
        );

        defaultPanel.add(coursPanel, "card2");

        instructorLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        instructorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructorLabel.setText("Instructor");

        instructorCreateButton.setText("Create");
        instructorCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorCreateButtonActionPerformed(evt);
            }
        });

        instructorReadButton.setText("Read");
        instructorReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorReadButtonActionPerformed(evt);
            }
        });

        instructorDeleteButton.setText("Delete");
        instructorDeleteButton.setToolTipText("");
        instructorDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorDeleteButtonActionPerformed(evt);
            }
        });

        instructorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        instructorScrollPane.setViewportView(instructorTable);

        javax.swing.GroupLayout instrructorPanelLayout = new javax.swing.GroupLayout(instrructorPanel);
        instrructorPanel.setLayout(instrructorPanelLayout);
        instrructorPanelLayout.setHorizontalGroup(
            instrructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(instrructorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructorCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructorReadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructorDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(instructorScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        instrructorPanelLayout.setVerticalGroup(
            instrructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrructorPanelLayout.createSequentialGroup()
                .addComponent(instructorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instructorScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(instrructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructorCreateButton)
                    .addComponent(instructorReadButton)
                    .addComponent(instructorDeleteButton))
                .addContainerGap())
        );

        defaultPanel.add(instrructorPanel, "card2");

        customerLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        customerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerLabel.setText("Customers");

        customerCreateButton.setText("Create");
        customerCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCreateButtonActionPerformed(evt);
            }
        });

        customerReadButton.setText("Read");
        customerReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerReadButtonActionPerformed(evt);
            }
        });

        customerDeleteButton.setText("Delete");
        customerDeleteButton.setToolTipText("");
        customerDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDeleteButtonActionPerformed(evt);
            }
        });

        warningLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel.setText("This isn't implementet and will be add in on the next update!");
        customerScrollPane.setViewportView(warningLabel);

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerReadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(customerScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addComponent(customerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerCreateButton)
                    .addComponent(customerReadButton)
                    .addComponent(customerDeleteButton))
                .addContainerGap())
        );

        defaultPanel.add(customerPanel, "card2");

        coursLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coursLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coursLabel1.setText("Help");

        jLabel1.setText("Are you sure ");

        jLabel2.setText("their is no help");

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coursLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(281, 281, 281))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addComponent(coursLabel1)
                .addGap(65, 65, 65)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        defaultPanel.add(helpPanel, "card2");

        coursLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coursLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coursLabel2.setText("About");

        jLabel3.setText("Welcome to Holiday Paradise Managing Program");

        jLabel4.setText("credits Benedict Goldhorn ");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coursLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(281, 281, 281))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addComponent(coursLabel2)
                .addGap(65, 65, 65)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        defaultPanel.add(aboutPanel, "card2");

        getContentPane().add(defaultPanel, "card2");

        FileMenu.setText("FILE");

        exitMenuItem.setText("Exit program");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(exitMenuItem);

        jMenuBar.add(FileMenu);

        basicDataMenu.setText("BASIC DATA");

        instructorMenuItem.setText("Manage instructores");
        instructorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorMenuItemActionPerformed(evt);
            }
        });
        basicDataMenu.add(instructorMenuItem);

        customerMenuItem.setText("Manage customeres");
        customerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMenuItemActionPerformed(evt);
            }
        });
        basicDataMenu.add(customerMenuItem);

        coursMenuItem.setText("Manage courses");
        coursMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursMenuItemActionPerformed(evt);
            }
        });
        basicDataMenu.add(coursMenuItem);

        jMenuBar.add(basicDataMenu);

        helpMenu.setText("HELP");

        helpMenuItem.setText("Help");
        helpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(helpMenuItem);

        AboutMenuItem.setText("About");
        AboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(AboutMenuItem);

        jMenuBar.add(helpMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void coursMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursMenuItemActionPerformed
        // TODO add your handling code here:
        defaultPanel.removeAll();
        defaultPanel.add(coursPanel);
        defaultPanel.repaint();
        defaultPanel.revalidate();
    }//GEN-LAST:event_coursMenuItemActionPerformed

    private void instructorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorMenuItemActionPerformed
        defaultPanel.removeAll();
        defaultPanel.add(instrructorPanel);
        defaultPanel.repaint();
        defaultPanel.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_instructorMenuItemActionPerformed

    private void customerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMenuItemActionPerformed
        // TODO add your handling code here:
        defaultPanel.removeAll();
        defaultPanel.add(customerPanel);
        defaultPanel.repaint();
        defaultPanel.revalidate();
    }//GEN-LAST:event_customerMenuItemActionPerformed

    private void helpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuItemActionPerformed
        // TODO add your handling code here:
        defaultPanel.removeAll();
        defaultPanel.add(helpPanel);
        defaultPanel.repaint();
        defaultPanel.revalidate();
    }//GEN-LAST:event_helpMenuItemActionPerformed

    private void coursReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursReadButtonActionPerformed
        // TODO add your handling code here:
            CoursData.getCoursList();
    }//GEN-LAST:event_coursReadButtonActionPerformed

    private void coursCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursCreateButtonActionPerformed
        // TODO add your handling code here:
        CreateCoursFrame create=new CreateCoursFrame();
        create.setVisible(true);
    }//GEN-LAST:event_coursCreateButtonActionPerformed

    private void coursDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursDeleteButtonActionPerformed
        // TODO add your handling code here:
        int action = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete that cours?", "Delete", JOptionPane.YES_NO_OPTION );
        if(action==0)
        {
            coursData.delteCoursefromTable();  
        }
    }//GEN-LAST:event_coursDeleteButtonActionPerformed

    private void instructorCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorCreateButtonActionPerformed
        // TODO add your handling code here:
        CreateInstructorFrame create =new CreateInstructorFrame();
        create.setVisible(true);
    }//GEN-LAST:event_instructorCreateButtonActionPerformed

    private void instructorReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorReadButtonActionPerformed
        // TODO add your handling code here:
        instructorData.showInstructors();
        
    }//GEN-LAST:event_instructorReadButtonActionPerformed

    private void instructorDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorDeleteButtonActionPerformed
        // TODO add your handling code here:
        int action = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete that cours?", "Delete", JOptionPane.YES_NO_OPTION );
        if(action==0)
        {
            instructorData.deleteInstructorfromTable();
        }
    }//GEN-LAST:event_instructorDeleteButtonActionPerformed

    private void customerCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCreateButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "This part isn't implementet yet!");
    }//GEN-LAST:event_customerCreateButtonActionPerformed

    private void customerReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerReadButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "This part isn't implementet yet!");
    }//GEN-LAST:event_customerReadButtonActionPerformed

    private void customerDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDeleteButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "This part isn't implementet yet!");
    }//GEN-LAST:event_customerDeleteButtonActionPerformed

    private void AboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuItemActionPerformed
        // TODO add your handling code here:
        defaultPanel.removeAll();
        defaultPanel.add(aboutPanel);
        defaultPanel.repaint();
        defaultPanel.revalidate();
    }//GEN-LAST:event_AboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JMenu basicDataMenu;
    private javax.swing.JButton coursCreateButton;
    private javax.swing.JButton coursDeleteButton;
    private javax.swing.JLabel coursLabel;
    private javax.swing.JLabel coursLabel1;
    private javax.swing.JLabel coursLabel2;
    private javax.swing.JMenuItem coursMenuItem;
    private javax.swing.JPanel coursPanel;
    private javax.swing.JButton coursReadButton;
    private javax.swing.JScrollPane coursScrollPane;
    public static javax.swing.JTable coursTable;
    private javax.swing.JButton customerCreateButton;
    private javax.swing.JButton customerDeleteButton;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JMenuItem customerMenuItem;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JButton customerReadButton;
    private javax.swing.JScrollPane customerScrollPane;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JPanel instrructorPanel;
    private javax.swing.JButton instructorCreateButton;
    private javax.swing.JButton instructorDeleteButton;
    private javax.swing.JLabel instructorLabel;
    private javax.swing.JMenuItem instructorMenuItem;
    private javax.swing.JButton instructorReadButton;
    private javax.swing.JScrollPane instructorScrollPane;
    public static javax.swing.JTable instructorTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
