/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import HolidayParadise.CoursData;
import javax.swing.*;
/**
 *
 * @author Benedict
 */
public class MainFrame extends javax.swing.JFrame {
    
    private CoursData coursData = new CoursData();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        defaultPanel.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultPanel = new javax.swing.JPanel();
        coursPanel = new javax.swing.JPanel();
        coursLabel = new javax.swing.JLabel();
        coursCreateButton = new javax.swing.JButton();
        coursReadButton = new javax.swing.JButton();
        coursDeleteButton = new javax.swing.JButton();
        coursScrollPane = new javax.swing.JScrollPane();
        coursTable = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        basicDataMenu = new javax.swing.JMenu();
        instructorMenuItem = new javax.swing.JMenuItem();
        customerMenuItem = new javax.swing.JMenuItem();
        coursMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        defaultPanel.setLayout(new java.awt.CardLayout());

        coursLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coursLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coursLabel.setText("Courses");

        coursCreateButton.setText("Create");
        coursCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursCreateButtonActionPerformed(evt);
            }
        });

        coursReadButton.setText("Read");
        coursReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursReadButtonActionPerformed(evt);
            }
        });

        coursDeleteButton.setText("Delete");
        coursDeleteButton.setToolTipText("");
        coursDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursDeleteButtonActionPerformed(evt);
            }
        });

        coursTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Begin", "End", "Date", "Weekday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        coursScrollPane.setViewportView(coursTable);

        javax.swing.GroupLayout coursPanelLayout = new javax.swing.GroupLayout(coursPanel);
        coursPanel.setLayout(coursPanelLayout);
        coursPanelLayout.setHorizontalGroup(
            coursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coursLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(coursPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coursCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coursReadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coursDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(coursScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        coursPanelLayout.setVerticalGroup(
            coursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursPanelLayout.createSequentialGroup()
                .addComponent(coursLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coursScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(coursPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coursCreateButton)
                    .addComponent(coursReadButton)
                    .addComponent(coursDeleteButton))
                .addContainerGap())
        );

        defaultPanel.add(coursPanel, "card2");

        getContentPane().add(defaultPanel, "card2");

        FileMenu.setText("FILE");

        exitMenuItem.setText("Exit program");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(exitMenuItem);

        jMenuBar.add(FileMenu);

        basicDataMenu.setText("BASIC DATA");

        instructorMenuItem.setText("Manage instructores");
        instructorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorMenuItemActionPerformed(evt);
            }
        });
        basicDataMenu.add(instructorMenuItem);

        customerMenuItem.setText("Manage customeres");
        customerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMenuItemActionPerformed(evt);
            }
        });
        basicDataMenu.add(customerMenuItem);

        coursMenuItem.setText("Manage courses");
        coursMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursMenuItemActionPerformed(evt);
            }
        });
        basicDataMenu.add(coursMenuItem);

        jMenuBar.add(basicDataMenu);

        helpMenu.setText("HELP");

        helpMenuItem.setText("Help");
        helpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(helpMenuItem);

        jMenuBar.add(helpMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void coursMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursMenuItemActionPerformed
        // TODO add your handling code here:
        defaultPanel.removeAll();
        defaultPanel.add(coursPanel);
        defaultPanel.repaint();
        defaultPanel.revalidate();
    }//GEN-LAST:event_coursMenuItemActionPerformed

    private void instructorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructorMenuItemActionPerformed

    private void customerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerMenuItemActionPerformed

    private void helpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMenuItemActionPerformed

    private void coursReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursReadButtonActionPerformed
        // TODO add your handling code here:
            CoursData.getCoursList();
    }//GEN-LAST:event_coursReadButtonActionPerformed

    private void coursCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursCreateButtonActionPerformed
        // TODO add your handling code here:
        CreateCoursFrame create=new CreateCoursFrame();
        create.setVisible(true);
    }//GEN-LAST:event_coursCreateButtonActionPerformed

    private void coursDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursDeleteButtonActionPerformed
        // TODO add your handling code here:
        int action = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete that cours?", "Delete", JOptionPane.YES_NO_OPTION );
        if(action==0)
        {
            coursData.delteCoursefromTable();  
        }
    }//GEN-LAST:event_coursDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu basicDataMenu;
    private javax.swing.JButton coursCreateButton;
    private javax.swing.JButton coursDeleteButton;
    private javax.swing.JLabel coursLabel;
    private javax.swing.JMenuItem coursMenuItem;
    private javax.swing.JPanel coursPanel;
    private javax.swing.JButton coursReadButton;
    private javax.swing.JScrollPane coursScrollPane;
    public static javax.swing.JTable coursTable;
    private javax.swing.JMenuItem customerMenuItem;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JMenuItem instructorMenuItem;
    private javax.swing.JMenuBar jMenuBar;
    // End of variables declaration//GEN-END:variables
}
