/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author Benedict
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        defaultPanel.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultPanel = new javax.swing.JPanel();
        instructorPanel = new javax.swing.JPanel();
        instructorLabel = new javax.swing.JLabel();
        instructorUpdateButton = new javax.swing.JButton();
        instructorCreateButton = new javax.swing.JButton();
        instructorReadButton = new javax.swing.JButton();
        instructorDeleteButton = new javax.swing.JButton();
        instructorScrollPane = new javax.swing.JScrollPane();
        jMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        basicDataMenu = new javax.swing.JMenu();
        instructorMenuItem = new javax.swing.JMenuItem();
        customerMenuItem = new javax.swing.JMenuItem();
        coursMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        defaultPanel.setLayout(new java.awt.CardLayout());

        instructorLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        instructorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructorLabel.setText("Instructor");

        instructorUpdateButton.setText("Update");

        instructorCreateButton.setText("Create");
        instructorCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorCreateButtonActionPerformed(evt);
            }
        });

        instructorReadButton.setText("Read");
        instructorReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorReadButtonActionPerformed(evt);
            }
        });

        instructorDeleteButton.setText("Delete");
        instructorDeleteButton.setToolTipText("");

        javax.swing.GroupLayout instructorPanelLayout = new javax.swing.GroupLayout(instructorPanel);
        instructorPanel.setLayout(instructorPanelLayout);
        instructorPanelLayout.setHorizontalGroup(
            instructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(instructorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructorCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructorUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructorReadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructorDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addComponent(instructorScrollPane)
        );
        instructorPanelLayout.setVerticalGroup(
            instructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructorPanelLayout.createSequentialGroup()
                .addComponent(instructorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instructorScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(instructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructorCreateButton)
                    .addComponent(instructorUpdateButton)
                    .addComponent(instructorReadButton)
                    .addComponent(instructorDeleteButton))
                .addContainerGap())
        );

        defaultPanel.add(instructorPanel, "card2");

        getContentPane().add(defaultPanel, "card2");

        FileMenu.setText("FILE");

        exitMenuItem.setText("Exit program");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(exitMenuItem);

        jMenuBar.add(FileMenu);

        basicDataMenu.setText("BASIC DATA");

        instructorMenuItem.setText("Manage instructores");
        instructorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorMenuItemActionPerformed(evt);
            }
        });
        basicDataMenu.add(instructorMenuItem);

        customerMenuItem.setText("Manage customeres");
        customerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMenuItemActionPerformed(evt);
            }
        });
        basicDataMenu.add(customerMenuItem);

        coursMenuItem.setText("Manage courses");
        coursMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursMenuItemActionPerformed(evt);
            }
        });
        basicDataMenu.add(coursMenuItem);

        jMenuBar.add(basicDataMenu);

        helpMenu.setText("HELP");

        helpMenuItem.setText("Help");
        helpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(helpMenuItem);

        jMenuBar.add(helpMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void coursMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursMenuItemActionPerformed

    private void instructorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorMenuItemActionPerformed
        // TODO add your handling code here:
        defaultPanel.removeAll();
        defaultPanel.add(instructorPanel);
        defaultPanel.repaint();
        defaultPanel.revalidate();
    }//GEN-LAST:event_instructorMenuItemActionPerformed

    private void customerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerMenuItemActionPerformed

    private void helpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMenuItemActionPerformed

    private void instructorReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorReadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructorReadButtonActionPerformed

    private void instructorCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorCreateButtonActionPerformed
        // TODO add your handling code here:
        CreateInstructorFrame create=new CreateInstructorFrame();
        create.setVisible(true);
    }//GEN-LAST:event_instructorCreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu basicDataMenu;
    private javax.swing.JMenuItem coursMenuItem;
    private javax.swing.JMenuItem customerMenuItem;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JButton instructorCreateButton;
    private javax.swing.JButton instructorDeleteButton;
    private javax.swing.JLabel instructorLabel;
    private javax.swing.JMenuItem instructorMenuItem;
    private javax.swing.JPanel instructorPanel;
    private javax.swing.JButton instructorReadButton;
    private javax.swing.JScrollPane instructorScrollPane;
    private javax.swing.JButton instructorUpdateButton;
    private javax.swing.JMenuBar jMenuBar;
    // End of variables declaration//GEN-END:variables
}
