/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HolidayParadise;

import java.time.LocalDate;
import javax.swing.*;

/**
 *
 * @author Benedict
 */
public class MainMenu extends javax.swing.JFrame {

    Data data =new Data();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() 
    {
        initComponents();
        addInstructorjLayeredPane.setVisible(true);
        sexButtonGroup.add(diversjRadioButton);
        sexButtonGroup.add(malejRadioButton1);
        sexButtonGroup.add(femalejRadioButton);
        
        workrelationButtonGroup.add(internjRadioButton);
        workrelationButtonGroup.add(externjRadioButton);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        sexButtonGroup = new javax.swing.ButtonGroup();
        workrelationButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addInstructorjLayeredPane = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        malejRadioButton1 = new javax.swing.JRadioButton();
        femalejRadioButton = new javax.swing.JRadioButton();
        diversjRadioButton = new javax.swing.JRadioButton();
        internjRadioButton = new javax.swing.JRadioButton();
        externjRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputNamejTextPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputBirtdatejTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputPrenamejTextPane = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        inputSpesificationjTextPane = new javax.swing.JTextPane();
        savejButton = new javax.swing.JButton();
        canclejButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CoursIDjPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        CoursjMenu = new javax.swing.JMenu();
        addCoursjMenu = new javax.swing.JMenu();
        updateCoursjMenu = new javax.swing.JMenu();
        deleteCoursMenu = new javax.swing.JMenu();
        showCoursjMenu = new javax.swing.JMenu();
        jMenu = new javax.swing.JMenu();
        addInstructorjMenu = new javax.swing.JMenu();
        updateInstructorjMenu = new javax.swing.JMenu();
        deleteInstructorjMenu = new javax.swing.JMenu();
        showInstructorjMenu = new javax.swing.JMenu();
        CustomerjMenu = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("HOLIDAY PARADISE");

        jLabel2.setText("Basic Data Management 2.0 Copyright 2019 Benedict Goldhorn, MNR 317664");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("prename:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("birthdate (JJJJ-MM-DD):");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("spesification:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Sex:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Workrelation:");

        malejRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        malejRadioButton1.setText("male");
        malejRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malejRadioButton1ActionPerformed(evt);
            }
        });

        femalejRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        femalejRadioButton.setText("female");
        femalejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalejRadioButtonActionPerformed(evt);
            }
        });

        diversjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        diversjRadioButton.setText("divers");
        diversjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diversjRadioButtonActionPerformed(evt);
            }
        });

        internjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        internjRadioButton.setText("intern");
        internjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internjRadioButtonActionPerformed(evt);
            }
        });

        externjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        externjRadioButton.setText("extern");
        externjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externjRadioButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(inputNamejTextPane);

        jScrollPane2.setViewportView(inputBirtdatejTextPane);

        jScrollPane3.setViewportView(inputPrenamejTextPane);

        jScrollPane4.setViewportView(inputSpesificationjTextPane);

        savejButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        savejButton.setText("save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        canclejButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canclejButton.setText("cancle");
        canclejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclejButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("CoursID");

        javax.swing.GroupLayout CoursIDjPanelLayout = new javax.swing.GroupLayout(CoursIDjPanel);
        CoursIDjPanel.setLayout(CoursIDjPanelLayout);
        CoursIDjPanelLayout.setHorizontalGroup(
            CoursIDjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CoursIDjPanelLayout.setVerticalGroup(
            CoursIDjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        addInstructorjLayeredPane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(malejRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(femalejRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(diversjRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(internjRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(externjRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(savejButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(canclejButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addInstructorjLayeredPane.setLayer(CoursIDjPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout addInstructorjLayeredPaneLayout = new javax.swing.GroupLayout(addInstructorjLayeredPane);
        addInstructorjLayeredPane.setLayout(addInstructorjLayeredPaneLayout);
        addInstructorjLayeredPaneLayout.setHorizontalGroup(
            addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addInstructorjLayeredPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(savejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(canclejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                        .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(internjRadioButton)
                                    .addComponent(malejRadioButton1))
                                .addGap(49, 49, 49)
                                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                                        .addComponent(femalejRadioButton)
                                        .addGap(70, 70, 70)
                                        .addComponent(diversjRadioButton))
                                    .addComponent(externjRadioButton)))
                            .addComponent(jLabel9)
                            .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                                    .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                        .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CoursIDjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        addInstructorjLayeredPaneLayout.setVerticalGroup(
            addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addInstructorjLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internjRadioButton)
                    .addComponent(externjRadioButton))
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(femalejRadioButton)
                    .addComponent(malejRadioButton1)
                    .addComponent(diversjRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoursIDjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(addInstructorjLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canclejButton)
                    .addComponent(savejButton))
                .addContainerGap())
        );

        CoursjMenu.setText("Cours");

        addCoursjMenu.setText("add");
        CoursjMenu.add(addCoursjMenu);

        updateCoursjMenu.setText("update");
        CoursjMenu.add(updateCoursjMenu);

        deleteCoursMenu.setText("delete");
        CoursjMenu.add(deleteCoursMenu);

        showCoursjMenu.setText("show");
        CoursjMenu.add(showCoursjMenu);

        jMenuBar1.add(CoursjMenu);

        jMenu.setText("Instructor");

        addInstructorjMenu.setText("add");
        addInstructorjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstructorjMenuActionPerformed(evt);
            }
        });
        jMenu.add(addInstructorjMenu);

        updateInstructorjMenu.setText("update");
        jMenu.add(updateInstructorjMenu);

        deleteInstructorjMenu.setText("delete");
        jMenu.add(deleteInstructorjMenu);

        showInstructorjMenu.setText("show");
        jMenu.add(showInstructorjMenu);

        jMenuBar1.add(jMenu);

        CustomerjMenu.setText("Customer");

        jMenu14.setText("add");
        CustomerjMenu.add(jMenu14);

        jMenu15.setText("update");
        CustomerjMenu.add(jMenu15);

        jMenu16.setText("delete");
        CustomerjMenu.add(jMenu16);

        jMenu17.setText("show");
        CustomerjMenu.add(jMenu17);

        jMenuBar1.add(CustomerjMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addInstructorjLayeredPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addInstructorjLayeredPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void externjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externjRadioButtonActionPerformed
        // TODO add your handling code here:
        this.setWorkrelation("extern");
    }//GEN-LAST:event_externjRadioButtonActionPerformed

    private void addInstructorjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstructorjMenuActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals("add"))
        {
            addInstructorjLayeredPane.setVisible(true);
        }
    }//GEN-LAST:event_addInstructorjMenuActionPerformed

    private void canclejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclejButtonActionPerformed
        // TODO add your handling code here:
        addInstructorjLayeredPane.setVisible(false);
    }//GEN-LAST:event_canclejButtonActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
        this.setName(this.inputNamejTextPane.getText());
        this.setPrename(this.inputPrenamejTextPane.getText());
        this.setSpesification(this.inputSpesificationjTextPane.getText());
        try
        {
            this.setBirthdate(LocalDate.parse(this.inputBirtdatejTextPane.getText()));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Wrong Input");
        }
        data.setInstructorList(this.getBirthdate(), this.getName(), this.getPrename(), this.getSex(), this.getSpesification(), this.getWorkrelation());
    }//GEN-LAST:event_savejButtonActionPerformed

    private void internjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internjRadioButtonActionPerformed
        // TODO add your handling code here:
        this.setWorkrelation("intern");
    }//GEN-LAST:event_internjRadioButtonActionPerformed

    private void malejRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malejRadioButton1ActionPerformed
        // TODO add your handling code here:
        this.setSex("male");
    }//GEN-LAST:event_malejRadioButton1ActionPerformed

    private void femalejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalejRadioButtonActionPerformed
        // TODO add your handling code here:
        this.setSex("female");
    }//GEN-LAST:event_femalejRadioButtonActionPerformed

    private void diversjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diversjRadioButtonActionPerformed
        // TODO add your handling code here:
        this.setSex("divers");
    }//GEN-LAST:event_diversjRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CoursIDjPanel;
    private javax.swing.JMenu CoursjMenu;
    private javax.swing.JMenu CustomerjMenu;
    private javax.swing.JMenu addCoursjMenu;
    private javax.swing.JLayeredPane addInstructorjLayeredPane;
    private javax.swing.JMenu addInstructorjMenu;
    private javax.swing.JButton canclejButton;
    private javax.swing.JMenu deleteCoursMenu;
    private javax.swing.JMenu deleteInstructorjMenu;
    private javax.swing.JRadioButton diversjRadioButton;
    private javax.swing.JRadioButton externjRadioButton;
    private javax.swing.JRadioButton femalejRadioButton;
    private javax.swing.JTextPane inputBirtdatejTextPane;
    private javax.swing.JTextPane inputNamejTextPane;
    private javax.swing.JTextPane inputPrenamejTextPane;
    private javax.swing.JTextPane inputSpesificationjTextPane;
    private javax.swing.JRadioButton internjRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton malejRadioButton1;
    private javax.swing.JButton savejButton;
    private javax.swing.ButtonGroup sexButtonGroup;
    private javax.swing.JMenu showCoursjMenu;
    private javax.swing.JMenu showInstructorjMenu;
    private javax.swing.JMenu updateCoursjMenu;
    private javax.swing.JMenu updateInstructorjMenu;
    private javax.swing.ButtonGroup workrelationButtonGroup;
    // End of variables declaration//GEN-END:variables
    
    private String name;
    private String prename;
    private String sex;
    private String workrelation;
    private String spesification;
    private LocalDate birthdate;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrename() {
        return prename;
    }

    public void setPrename(String prename) {
        this.prename = prename;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getWorkrelation() {
        return workrelation;
    }

    public void setWorkrelation(String workrelation) {
        this.workrelation = workrelation;
    }

    public String getSpesification() {
        return spesification;
    }

    public void setSpesification(String spesification) {
        this.spesification = spesification;
    }

    public LocalDate getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
    }
       
}
