/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Logic.CoursData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Benedict
 */
public class CreateCoursFrame extends javax.swing.JFrame {
    
    private String name;
    private String begin;
    private String end;
    private LocalDate date;
    private String weekday="";
    private Pattern pattern;
    private Matcher matcher;
    private String regex="^(0[0-9]|1[0-9]|2[0-3]|[0-9]):[0-5][0-9]$";    
    
    private CoursData data;
    
    /**
     * Creates new form CreateCours
     */
    public CreateCoursFrame() {
        initComponents();
        weekdayButtonGroup.add(mondayRadioButton);
        weekdayButtonGroup.add(tuesdayRadioButton);
        weekdayButtonGroup.add(wednesdayRadioButton);
        weekdayButtonGroup.add(thursdayRadioButton);
        weekdayButtonGroup.add(fridayRadioButton);
        weekdayButtonGroup.add(saturdayRadioButton);
        weekdayButtonGroup.add(sundayRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weekdayButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        beginTextField = new javax.swing.JTextField();
        endTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mondayRadioButton = new javax.swing.JRadioButton();
        tuesdayRadioButton = new javax.swing.JRadioButton();
        wednesdayRadioButton = new javax.swing.JRadioButton();
        thursdayRadioButton = new javax.swing.JRadioButton();
        fridayRadioButton = new javax.swing.JRadioButton();
        saturdayRadioButton = new javax.swing.JRadioButton();
        sundayRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Cours");

        jLabel2.setText("Name:");

        jLabel3.setText("Begin:");

        jLabel4.setText("End:");

        beginTextField.setText("HH:MM");

        endTextField.setText("HH:MM");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("Cancle");
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Date:");

        dateTextField.setText("JJJJ-MM-DD");

        jLabel6.setText("Weekday:");

        mondayRadioButton.setText("Monday");
        mondayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayRadioButtonActionPerformed(evt);
            }
        });

        tuesdayRadioButton.setText("Tuesday");
        tuesdayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayRadioButtonActionPerformed(evt);
            }
        });

        wednesdayRadioButton.setText("Wednesday");
        wednesdayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayRadioButtonActionPerformed(evt);
            }
        });

        thursdayRadioButton.setText("Thursday");
        thursdayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayRadioButtonActionPerformed(evt);
            }
        });

        fridayRadioButton.setText("Friday");
        fridayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayRadioButtonActionPerformed(evt);
            }
        });

        saturdayRadioButton.setText("Saturday");
        saturdayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayRadioButtonActionPerformed(evt);
            }
        });

        sundayRadioButton.setText("Sunday");
        sundayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sundayRadioButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(beginTextField)
                                        .addComponent(endTextField)
                                        .addComponent(dateTextField))))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wednesdayRadioButton)
                                    .addComponent(mondayRadioButton)
                                    .addComponent(fridayRadioButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saturdayRadioButton)
                                    .addComponent(tuesdayRadioButton)
                                    .addComponent(thursdayRadioButton))))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(endTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mondayRadioButton)
                    .addComponent(tuesdayRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wednesdayRadioButton)
                    .addComponent(thursdayRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fridayRadioButton)
                    .addComponent(saturdayRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sundayRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(cancleButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        name=nameTextField.getText();
        begin=beginTextField.getText();
        end=endTextField.getText();
        boolean error=false;
        pattern = Pattern.compile(regex);
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The cours has no name");
            error=true;
        }
        try
        {
            date=LocalDate.parse(dateTextField.getText());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "The date is inncorrect");
            error=true;
        }
        matcher = pattern.matcher(begin);
        if(!(matcher.find()&& matcher.group().equals(begin)))
        {
            JOptionPane.showMessageDialog(null, "The starting time of the cours is incorect");
            error=true;
        }
        matcher=pattern.matcher(end);
        if(!(matcher.find()&&matcher.group().equals(end)))
        {
            JOptionPane.showMessageDialog(null, "The ending time of the cours is incorect");
            error=true;
        }
        if(weekday.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Pleas select a weekday ");
            error=true;
        }
        if(error==false)
        {
            data = new CoursData();
            try 
            {
                data.addCours(name, begin, end, date, weekday);
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(CreateCoursFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
            
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void mondayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayRadioButtonActionPerformed
        // TODO add your handling code here:
        weekday="Mon";
    }//GEN-LAST:event_mondayRadioButtonActionPerformed

    private void tuesdayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayRadioButtonActionPerformed
        // TODO add your handling code here:
        weekday="Tue";
    }//GEN-LAST:event_tuesdayRadioButtonActionPerformed

    private void wednesdayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayRadioButtonActionPerformed
        // TODO add your handling code here:
        weekday="Wed";
    }//GEN-LAST:event_wednesdayRadioButtonActionPerformed

    private void thursdayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayRadioButtonActionPerformed
        // TODO add your handling code here:
        weekday="Thu";
    }//GEN-LAST:event_thursdayRadioButtonActionPerformed

    private void fridayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayRadioButtonActionPerformed
        // TODO add your handling code here:
        weekday="Fri";
    }//GEN-LAST:event_fridayRadioButtonActionPerformed

    private void saturdayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayRadioButtonActionPerformed
        // TODO add your handling code here:
        weekday="Sat";
    }//GEN-LAST:event_saturdayRadioButtonActionPerformed

    private void sundayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayRadioButtonActionPerformed
        // TODO add your handling code here:
        weekday="Sun";
    }//GEN-LAST:event_sundayRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beginTextField;
    private javax.swing.JButton cancleButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField endTextField;
    private javax.swing.JRadioButton fridayRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton mondayRadioButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton saturdayRadioButton;
    private javax.swing.JRadioButton sundayRadioButton;
    private javax.swing.JRadioButton thursdayRadioButton;
    private javax.swing.JRadioButton tuesdayRadioButton;
    private javax.swing.JRadioButton wednesdayRadioButton;
    private javax.swing.ButtonGroup weekdayButtonGroup;
    // End of variables declaration//GEN-END:variables
}
