/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Benedict
 */
public class CreateCustomerFrame extends javax.swing.JFrame {
    
    private String title="";
    private String name;
    private String prename;
    private String sex="";
    private LocalDate birthdate; 
    /**
     * Creates new form CreateCustomer
     */
    public CreateCustomerFrame() {
        initComponents();
        titleButtonGroup.add(mrRadioButton);
        titleButtonGroup.add(msRadioButton);
        titleButtonGroup.add(drRadioButton);
        sexButtonGroup.add(maleRadioButton);
        sexButtonGroup.add(femaleRadioButton);
        sexButtonGroup.add(diversRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleButtonGroup = new javax.swing.ButtonGroup();
        sexButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PrenameTextFiel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        birthdateTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mrRadioButton = new javax.swing.JRadioButton();
        msRadioButton = new javax.swing.JRadioButton();
        drRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        diversRadioButton = new javax.swing.JRadioButton();
        cancleButton = new javax.swing.JButton();
        createButto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cretae Instructor");

        jLabel2.setText("Name:");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Prename:");

        PrenameTextFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenameTextFielActionPerformed(evt);
            }
        });

        jLabel4.setText("Birthdate:");

        birthdateTextField.setText("JJJJ-MM-DD");

        jLabel5.setText("Title:");

        mrRadioButton.setText("Mr");

        msRadioButton.setText("Ms");
        msRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msRadioButtonActionPerformed(evt);
            }
        });

        drRadioButton.setText("Dr");

        jLabel6.setText("Sex:");

        maleRadioButton.setText("Male");

        femaleRadioButton.setText("Female");

        diversRadioButton.setText("Divers");

        cancleButton.setText("cancle");
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        createButto.setText("create");
        createButto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createButto)
                        .addGap(132, 132, 132)
                        .addComponent(cancleButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(maleRadioButton)
                                .addGap(4, 4, 4)
                                .addComponent(femaleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(diversRadioButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(mrRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(msRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(drRadioButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTextField)
                                    .addComponent(PrenameTextFiel)
                                    .addComponent(birthdateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PrenameTextFiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(birthdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrRadioButton)
                    .addComponent(msRadioButton)
                    .addComponent(drRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton)
                    .addComponent(diversRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancleButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createButto)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void PrenameTextFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenameTextFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenameTextFielActionPerformed

    private void msRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msRadioButtonActionPerformed

    private void createButtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtoActionPerformed
        // TODO add your handling code here:
        boolean error=false;
        name=nameTextField.getText();
        prename=PrenameTextFiel.getText();
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Name is missing");
            error=true;
        }
        if(prename.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "prename is missing");
            error=true;
        }
        try
        {
            birthdate=LocalDate.parse(birthdateTextField.getText());
        }
        catch(Exception e)
        {
            error=true;
            JOptionPane.showMessageDialog(null, "Birthdate is inncorect");
        }
        if(sex.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Sex is missing");
            error=true;
        }
        if(title.equals(""))
        {
            JOptionPane.showMessageDialog(null, "title is missing");
            error=true;
        }
        if(error==false)
        {
            this.dispose();
        }
    }//GEN-LAST:event_createButtoActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PrenameTextFiel;
    private javax.swing.JTextField birthdateTextField;
    private javax.swing.JButton cancleButton;
    private javax.swing.JButton createButto;
    private javax.swing.JRadioButton diversRadioButton;
    private javax.swing.JRadioButton drRadioButton;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton mrRadioButton;
    private javax.swing.JRadioButton msRadioButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.ButtonGroup sexButtonGroup;
    private javax.swing.ButtonGroup titleButtonGroup;
    // End of variables declaration//GEN-END:variables
}
